import {z} from 'zod';
import {getDb} from '@/db';
import {currentOwner,apiError,fail,sameOrigin,readBody,payloadHash} from '@/lib/server';
import {EXPENSE_CATEGORIES} from '@/lib/finance';
import {isStatPeriod,statisticRange} from '@/lib/statistics';
export const dynamic='force-dynamic';
const schema=z.object({requestKey:z.string().uuid(),amount:z.number().int().min(1).max(100000000),category:z.string().refine(v=>Object.hasOwn(EXPENSE_CATEGORIES,v)),description:z.string().trim().min(2).max(300),paidAt:z.number().int().min(946684800000),paymentSource:z.enum(['bank','external_cash','drawer'])}).strict();
export async function GET(request:Request){const owner=await currentOwner();if(!owner)return fail('შესვლა აუცილებელია.',401);const period=new URL(request.url).searchParams.get('period')??'month';if(!isStatPeriod(period))return fail('აირჩიე სწორი პერიოდი.');try{const range=statisticRange(period),db=getDb();const [rows,sum]=await db.batch([db.prepare('SELECT * FROM expenses WHERE owner_id=? AND paid_at>=? AND paid_at<? ORDER BY paid_at DESC LIMIT 500').bind(owner,range.start,range.end),db.prepare('SELECT COALESCE(SUM(amount),0) AS total,COUNT(*) AS count FROM expenses WHERE owner_id=? AND paid_at>=? AND paid_at<? AND voided_at IS NULL').bind(owner,range.start,range.end)]);return Response.json({expenses:rows.results,total:(sum.results[0] as {total:number}).total,count:(sum.results[0] as {count:number}).count,range},{headers:{'Cache-Control':'no-store'}});}catch(e){return apiError(e);}}
export async function POST(request:Request){const owner=await currentOwner();if(!owner)return fail('შესვლა აუცილებელია.',401);if(!sameOrigin(request))return fail('მოთხოვნა ვერ დადასტურდა.',403);let parsed;try{parsed=schema.safeParse(await readBody(request));}catch{return fail('მონაცემები არასწორია.');}if(!parsed.success)return fail('შეამოწმე თანხა, თარიღი და ველები.');const b=parsed.data;try{const db=getDb(),hash=await payloadHash(b),previous=await db.prepare('SELECT * FROM expenses WHERE owner_id=? AND request_key=?').bind(owner,b.requestKey).first();if(previous)return previous.request_hash===hash?Response.json({expense:previous}):fail('ეს მცდელობა უკვე გამოყენებულია. განაახლე ფორმა.',409);const now=Date.now();if(b.paidAt>now+60000)return fail('მომავლის თარიღით გადახდილი ხარჯი ვერ ჩაიწერება.');const id=crypto.randomUUID();const r=await db.prepare(`INSERT INTO expenses (id,owner_id,request_key,request_hash,amount,category,description,paid_at,created_at,payment_source,shift_id) SELECT ?,?,?,?,?,?,?,?,?,?,CASE WHEN ?='drawer' THEN (SELECT id FROM cash_shifts WHERE active_owner=? AND closed_at IS NULL) ELSE NULL END WHERE ?!='drawer' OR EXISTS(SELECT 1 FROM cash_shifts WHERE active_owner=? AND closed_at IS NULL AND CAST(opened_at/60000 AS INTEGER)<=CAST(?/60000 AS INTEGER)) ON CONFLICT(owner_id,request_key) DO NOTHING`).bind(id,owner,b.requestKey,hash,b.amount,b.category,b.description,b.paidAt,now,b.paymentSource,b.paymentSource,owner,b.paymentSource,owner,b.paidAt).run();const saved=await db.prepare('SELECT * FROM expenses WHERE owner_id=? AND request_key=?').bind(owner,b.requestKey).first();if(!saved)return fail('ჯერ გახსენი სალაროს ცვლა. თარიღი ცვლის დაწყებაზე ადრე არ უნდა იყოს.',409);if(saved.request_hash!==hash)return fail('ეს მცდელობა უკვე გამოყენებულია. განაახლე ფორმა.',409);return Response.json({expense:saved},{status:r.meta.changes?201:200});}catch(e){return apiError(e);}}
export async function PATCH(request:Request){const owner=await currentOwner();if(!owner)return fail('შესვლა აუცილებელია.',401);if(!sameOrigin(request))return fail('მოთხოვნა ვერ დადასტურდა.',403);let b;try{b=z.object({id:z.string().uuid(),reason:z.string().trim().min(3).max(300)}).strict().parse(await readBody(request));}catch{return fail('მიუთითე გაუქმების მიზეზი.');}try{const db=getDb(),row=await db.prepare('SELECT * FROM expenses WHERE id=? AND owner_id=?').bind(b.id,owner).first();if(!row)return fail('ხარჯი ვერ მოიძებნა.',404);if(row.voided_at)return row.void_reason===b.reason?Response.json({ok:true}):fail('ხარჯი უკვე გაუქმებულია.',409);const r=await db.prepare('UPDATE expenses SET voided_at=?,void_reason=? WHERE id=? AND owner_id=? AND voided_at IS NULL AND (shift_id IS NULL OR EXISTS(SELECT 1 FROM cash_shifts WHERE cash_shifts.id=expenses.shift_id AND active_owner=? AND closed_at IS NULL))').bind(Date.now(),b.reason,b.id,owner,owner).run();return r.meta.changes?Response.json({ok:true}):fail('დახურული ცვლის ხარჯის შეცვლა დაუშვებელია.',409);}catch(e){return apiError(e);}}
