import './support/register.mjs';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {configure} from './support/runtime.mjs';
import {DEFAULT_SETTINGS} from '../lib/menu.ts';
import {deliveryZone,preparation,reconcileOrder,QUEUE_SQL} from '../lib/operations.ts';
import {calculateOrder,orderInput,settingsInput} from '../lib/order-validation.ts';
import {operatingResult,SHIFT_SELECT} from '../lib/finance.ts';
import * as orderApi from '../app/api/orders/route.ts';
import * as orderItemApi from '../app/api/orders/[id]/route.ts';
import * as expenseApi from '../app/api/admin/expenses/route.ts';
import * as shiftApi from '../app/api/admin/shifts/route.ts';
import * as statisticsApi from '../app/api/admin/statistics/route.ts';
function db(){const d=new DatabaseSync(':memory:');for(const f of readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())d.exec(readFileSync(new URL('../drizzle/'+f,import.meta.url),'utf8'));configure(d);d.prepare('INSERT INTO products(id,owner_id,name,description,ingredients,allergens,category,price,cost,image,available,min_quantity,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run('p','owner-a','ქალაქური','','','','khinkali',200,80,'',1,5,Date.now());return d;}
function req(path,body,method='POST'){return new Request('https://test.example'+path,{method,headers:{origin:'https://test.example','content-type':'application/json'},body:JSON.stringify(body)});}
async function json(response,status=200){assert.equal(response.status,status,await response.clone().text());return response.json();}
function input(extra={}){return{requestKey:crypto.randomUUID(),name:'Test',phone:'+995555123456',address:'Test street 12',note:'',fulfillment:'pickup',source:'web',paymentMethod:'cash',expectedTotal:1000,items:[{id:'p',quantity:5}],...extra};}
async function create(extra={}){return(await json(await orderApi.POST(req('/api/orders',input(extra))),201)).order;}
async function open(openingCash=1000){const body={action:'open',requestKey:crypto.randomUUID(),openingCash,note:''};const r=await json(await shiftApi.POST(req('/api/admin/shifts',body)));return{body,shift:r.shift};}
async function collect(o,destination='drawer'){return orderItemApi.PATCH(req('/api/orders/'+o.id,{action:'collect',cashReceived:2000,cashDestination:destination},'PATCH'),{params:Promise.resolve({id:o.id})});}
async function close(id,countedCash){const body={action:'close',requestKey:crypto.randomUUID(),id,countedCash,note:'counted'};return{body,response:await shiftApi.POST(req('/api/admin/shifts',body))};}
test('zones handle edge/overlap/disabled/outside; settings reject invalid polygons and duplicate IDs',()=>{const polygon=[{lat:0,lng:0},{lat:0,lng:1},{lat:1,lng:1},{lat:1,lng:0}],a={id:'a',name:'AA',nameEn:'AA',nameRu:'AA',enabled:true,fee:400,minutes:15,minimum:0,polygon},b={...a,id:'b'};for(const point of [{lat:.5,lng:.5},{lat:0,lng:0},{lat:.5,lng:1}])assert.equal(deliveryZone(point,[a,b]).id,'a');assert.equal(deliveryZone({lat:2,lng:2},[a]),undefined);assert.equal(deliveryZone({lat:.5,lng:.5},[{...a,enabled:false},b]).id,'b');assert.equal(deliveryZone({lat:NaN,lng:0},[a]),undefined);assert.equal(settingsInput.safeParse({...DEFAULT_SETTINGS,zones:[a,a]}).success,false);assert.equal(settingsInput.safeParse({...DEFAULT_SETTINGS,zones:[{...a,polygon:[{lat:0,lng:0},{lat:0,lng:0},{lat:0,lng:0}]}]}).success,false);});
test('zone pricing is authoritative, pickup ignores zone minimum and malformed coordinates fail',()=>{const p={id:'p',name:'A',available:true,minQuantity:5,price:200,cost:80,category:'khinkali'},zone={...DEFAULT_SETTINGS.zones[0],minimum:5000};const settings={...DEFAULT_SETTINGS,zones:[zone]};assert.equal(calculateOrder(input(),[p],settings).total,1000);assert.throws(()=>calculateOrder(input({fulfillment:'delivery',point:{lat:0,lng:0}}),[p],settings),/ზონის/);assert.equal(orderInput.safeParse(input({point:{lat:91,lng:0}})).success,false);});
test('reorder uses new price/minimum, removes unavailable/deleted and never copies monetary snapshots',()=>{const old=[{id:'a',name:'A',quantity:5,price:100,cost:20},{id:'b',name:'B',quantity:5,price:100},{id:'deleted',name:'D',quantity:5,price:100}],products=[{id:'a',name:'A',available:true,minQuantity:10,price:200},{id:'b',name:'B',available:false,minQuantity:5,price:100}];const r=reconcileOrder(old,products);assert.deepEqual(r.cart,{a:10});assert.deepEqual(r.changes.map(c=>c.reason),['minimum','price','unavailable','missing']);assert.deepEqual(reconcileOrder(old,[]).cart,{});});
test('queue excludes ready/drinks, survives malformed legacy JSON, counts prior days and >300 orders',()=>{const d=db();const insert=d.prepare("INSERT INTO orders(id,owner_id,request_key,request_hash,customer_name,phone,address,note,fulfillment,items_json,subtotal,delivery_fee,total,status,payment_status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");let n=0;function add(items,status='received',owner='owner-a'){const id=String(++n);insert.run(id,owner,id,id,'','','','','pickup',items,0,0,0,status,'cash_due',1,1);}for(let i=0;i<351;i++)add('[{"quantity":5,"category":"khinkali"}]');for(const items of ['bad','["bad"]','{}','[{"quantity":-99}]','[{"quantity":1.5}]','[{"quantity":900,"category":"drink"}]'])add(items);add('[{"quantity":1000}]','ready');add('[{"quantity":1000}]','received','owner-b');assert.equal(d.prepare(QUEUE_SQL).get('owner-a').units,1755);assert.equal(preparation(DEFAULT_SETTINGS,60,5),40);assert.equal(preparation(DEFAULT_SETTINGS,0,5),25);d.close();});
test('actual order endpoint snapshots pin/zone/ETA, redacts cost, idempotent retry precedes changed prices',async()=>{const d=db(),body=input({fulfillment:'delivery',point:{lat:41.65,lng:41.638},expectedTotal:1400});const first=await json(await orderApi.POST(req('/api/orders',body)),201);assert.equal(first.order.delivery_fee,400);assert.equal(first.order.travel_minutes,15);assert.equal(first.order.prep_minutes,40);assert.equal(first.order.delivery_lat,body.point.lat);assert.equal(first.order.items[0].cost,undefined);d.prepare('UPDATE products SET price=999 WHERE id=?').run('p');const replay=await json(await orderApi.POST(req('/api/orders',body)));assert.equal(replay.order.id,first.order.id);assert.equal(replay.order.total,1400);assert.equal((await orderApi.POST(req('/api/orders',{...body,expectedTotal:999}))).status,409);assert.equal((await orderApi.POST(req('/api/orders',input({fulfillment:'delivery',point:{lat:0,lng:0}})))).status,409);d.close();});
test('cash shifts collect sale not tender; close is atomic, immutable and replayable; courier cash excluded',async()=>{const d=db(),o=await create();assert.equal((await collect(o)).status,409);const s=await open();await json(await shiftApi.POST(req('/api/admin/shifts',s.body)));assert.equal((await shiftApi.POST(req('/api/admin/shifts',{...s.body,openingCash:999}))).status,409);assert.equal((await shiftApi.POST(req('/api/admin/shifts',{...s.body,requestKey:crypto.randomUUID()}))).status,409);await json(await collect(o));const courier=await create();await json(await collect(courier,'courier'));let row=d.prepare(SHIFT_SELECT+' WHERE id=?').get(s.shift.id);assert.equal(row.expected,2000);assert.equal(row.sales,1000);const c=await close(s.shift.id,1950);await json(c.response);await json(await shiftApi.POST(req('/api/admin/shifts',c.body)));row=d.prepare(SHIFT_SELECT+' WHERE id=?').get(s.shift.id);assert.equal(row.expected_cash,2000);assert.equal(row.difference,-50);const next=await create();assert.equal((await collect(next)).status,409);assert.equal(d.prepare('SELECT expected_cash FROM cash_shifts WHERE id=?').get(s.shift.id).expected_cash,2000);d.close();});
test('drawer expense same opening minute, cash movements, void guard, and net expense report',async()=>{const d=db(),s=await open(2000);const o=await create();await json(await collect(o));const body={requestKey:crypto.randomUUID(),amount:300,category:'courier',description:'Courier fee',paidAt:Math.floor(Date.now()/60000)*60000,paymentSource:'drawer'};const expense=(await json(await expenseApi.POST(req('/api/admin/expenses',body)),201)).expense;await json(await expenseApi.POST(req('/api/admin/expenses',body)));assert.equal((await expenseApi.POST(req('/api/admin/expenses',{...body,amount:999}))).status,409);assert.equal((await expenseApi.POST(req('/api/admin/expenses',{...body,requestKey:crypto.randomUUID(),category:'toString'}))).status,400);const move={action:'move',requestKey:crypto.randomUUID(),id:s.shift.id,amount:100,kind:'out',note:'Bank deposit'};await json(await shiftApi.POST(req('/api/admin/shifts',move)));await json(await shiftApi.POST(req('/api/admin/shifts',move)));assert.equal(d.prepare(SHIFT_SELECT+' WHERE id=?').get(s.shift.id).expected,2600);const report=await json(await statisticsApi.GET(new Request('https://test.example/api/admin/statistics?period=today')));assert.equal(report.summary.expenses,300);assert.equal(report.summary.operatingResult,300);await json((await close(s.shift.id,2600)).response);assert.equal((await expenseApi.PATCH(req('/api/admin/expenses',{id:expense.id,reason:'Wrong entry'},'PATCH'))).status,409);assert.equal((await shiftApi.POST(req('/api/admin/shifts',{...move,requestKey:crypto.randomUUID()}))).status,409);d.close();});
test('owner isolation and cross-origin mutations are rejected; unknown cost stays unknown',async()=>{const d=db(),s=await open(),o=await create();configure(d,'owner-b');assert.equal((await collect(o)).status,404);assert.equal((await close(s.shift.id,0)).response.status,404);assert.equal((await json(await shiftApi.GET())).shifts.length,0);const bad=new Request('https://test.example/api/admin/shifts',{method:'POST',headers:{origin:'https://evil.example'},body:JSON.stringify({action:'open'})});assert.equal((await shiftApi.POST(bad)).status,403);assert.equal(operatingResult(1000,null,100),null);assert.equal(operatingResult(1000,0,100),900);assert.equal(operatingResult(1000,800,500),-300);d.close();});
