"use client";
import {useState} from "react";
import {Plus,Pencil,ImagePlus,Package,Check} from "lucide-react";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Switch} from "@/components/ui/switch";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from "@/components/ui/table";
import {AdminShell,ErrorNote,Loading} from "./site-shell";
import {api,useCatalog,productPayload} from "@/lib/client";
import {CATEGORIES,money,type Product} from "@/lib/menu";
const blank:Product={id:"",name:"",description:"",ingredients:"",allergens:"",category:"khinkali",price:0,cost:0,image:"",available:true,minQuantity:5,updatedAt:0};
export default function ProductAdmin(){const{data,error,load}=useCatalog(true),[edit,setEdit]=useState<Product|null>(null),[price,setPrice]=useState(""),[cost,setCost]=useState(""),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[failure,setFailure]=useState(""),[notice,setNotice]=useState("");
 function open(p:Product){setEdit({...p});setPrice(p.price?String(p.price/100):"");setCost(String((p.cost||0)/100));setFailure("");}
 async function upload(file?:File){if(!file||!edit)return;setUploading(true);setFailure("");try{if(file.size>6000000)throw new Error("ფოტო მაქსიმუმ 6 MB უნდა იყოს.");const f=new FormData();f.append("file",file);const r=await api<{image:string}>("/api/images",{method:"POST",body:f});setEdit(p=>p?{...p,image:r.image}:p);}catch(e){setFailure((e as Error).message);}finally{setUploading(false);}}
 async function save(e:React.FormEvent){e.preventDefault();if(!edit||busy||uploading)return;setBusy(true);setFailure("");try{const p={...edit,price:Math.round(Number(price)*100),cost:Math.round(Number(cost)*100)};if(!Number.isFinite(p.price)||p.price<=0||!Number.isFinite(p.cost)||p.cost<0)throw new Error("შეამოწმე ფასი და თვითღირებულება.");await api(edit.id?`/api/admin/products/${edit.id}`:"/api/admin/products",{method:edit.id?"PATCH":"POST",body:JSON.stringify(productPayload(p))});setEdit(null);setNotice("პროდუქტი შენახულია — ცვლილება საიტსა და სალაროშიც გამოჩნდება.");await load();}catch(e){setFailure((e as Error).message);}finally{setBusy(false);}}
 async function toggle(p:Product){setBusy(true);setFailure("");try{await api(`/api/admin/products/${p.id}`,{method:"PATCH",body:JSON.stringify({...productPayload(p),available:!p.available})});await load();}catch(e){setFailure((e as Error).message);}finally{setBusy(false);}}
 return <AdminShell active="/admin/products"><div className="page-heading"><div><p className="eyebrow">შენი მენიუ</p><h1>პროდუქტები</h1><p>ფოტოები, ფასები და ხელმისაწვდომობა ერთ სივრცეში.</p></div><button className="primary" onClick={()=>open(blank)}><Plus size={19}/> პროდუქტის დამატება</button></div><ErrorNote message={error||(!edit?failure:"")} onRetry={()=>void load()}/>{notice&&<p className="saved-note" role="status"><Check size={18}/>{notice}</p>}{!data?<Loading/>:<><div className="stats-row"><div><span>მენიუში</span><strong>{data.products.length}</strong></div><div><span>ხელმისაწვდომია</span><strong>{data.products.filter(p=>p.available).length}</strong></div><div><span>დროებით ამოწურულია</span><strong>{data.products.filter(p=>!p.available).length}</strong></div></div><div className="table-card"><Table><TableHeader><TableRow><TableHead>პროდუქტი</TableHead><TableHead>კატეგორია</TableHead><TableHead>თვითღირებულება</TableHead><TableHead>ფასი / ცალი</TableHead><TableHead>სხვაობა / ცალი</TableHead><TableHead>იყიდება</TableHead><TableHead><span className="sr-only">რედაქტირება</span></TableHead></TableRow></TableHeader><TableBody>{data.products.map(p=><TableRow key={p.id}><TableCell><div className="product-table-name">{p.image?<img src={p.image} alt="" width="56" height="56"/>:<Package size={30}/>}<div><strong>{p.name}</strong><small>მინ. {p.minQuantity} ცალი</small></div></div></TableCell><TableCell>{CATEGORIES[p.category]}</TableCell><TableCell>{money(p.cost||0)}</TableCell><TableCell><strong>{money(p.price)}</strong></TableCell><TableCell>{money(p.price-(p.cost||0))}</TableCell><TableCell><Switch checked={p.available} disabled={busy} onCheckedChange={()=>void toggle(p)} aria-label={`${p.name}: ხელმისაწვდომობა`}/></TableCell><TableCell><button className="icon-button" onClick={()=>open(p)} aria-label={`${p.name}: რედაქტირება`}><Pencil size={18}/></button></TableCell></TableRow>)}</TableBody></Table></div><p className="small-note">თვითღირებულება მომხმარებლის მენიუში არ ჩანს. სხვაობა წმინდა მოგება არ არის — დამატებითი ხარჯები ცალკე გასათვალისწინებელია. საწყისი მონაცემები საილუსტრაციოა.</p></>}
 <Dialog open={!!edit} onOpenChange={v=>{if(!v&&!busy&&!uploading)setEdit(null);}}><DialogContent className="edit-dialog"><DialogHeader><DialogTitle>{edit?.id?"პროდუქტის რედაქტირება":"ახალი პროდუქტი"}</DialogTitle><DialogDescription>ყველა ფასი მიუთითე ერთი ცალისთვის, ლარში.</DialogDescription></DialogHeader>{edit&&<form onSubmit={save}><fieldset disabled={busy||uploading}><div className="image-editor">{edit.image?<img src={edit.image} alt="პროდუქტის ფოტო"/>:<ImagePlus size={38}/>}<div><label className="secondary upload-label"><ImagePlus size={18}/>{uploading?"იტვირთება…":"ფოტოს ატვირთვა"}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>void upload(e.target.files?.[0])}/></label><p className="small-note">JPG, PNG, WebP · მაქს. 6 MB</p>{edit.image&&<button type="button" className="text-button" onClick={()=>setEdit({...edit,image:""})}>ფოტოს მოხსნა</button>}</div></div><div className="form-grid"><label className="field">დასახელება<input required minLength={2} maxLength={80} value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label className="field">კატეგორია<Select value={edit.category} onValueChange={v=>setEdit({...edit,category:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(CATEGORIES).map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select></label><label className="field">გასაყიდი ფასი ₾<input required type="number" step="0.01" min="0.01" max="10000" value={price} onChange={e=>setPrice(e.target.value)}/></label><label className="field">თვითღირებულება ₾<input required type="number" step="0.01" min="0" max="10000" value={cost} onChange={e=>setCost(e.target.value)}/></label></div><label className="field">მოკლე აღწერა<input maxLength={200} value={edit.description} onChange={e=>setEdit({...edit,description:e.target.value})}/></label><label className="field">შემადგენლობა<textarea maxLength={500} value={edit.ingredients} onChange={e=>setEdit({...edit,ingredients:e.target.value})}/></label><label className="field">ალერგენები<input maxLength={250} placeholder="მაგ.: ხორბალი, რძე" value={edit.allergens} onChange={e=>setEdit({...edit,allergens:e.target.value})}/></label><div className="form-grid"><label className="field">მინიმალური რაოდენობა<input required type="number" min="1" max="200" value={edit.minQuantity} onChange={e=>setEdit({...edit,minQuantity:Number(e.target.value)})}/></label><div className="switch-field"><label htmlFor="product-available">ხელმისაწვდომია</label><Switch id="product-available" checked={edit.available} onCheckedChange={v=>setEdit({...edit,available:v})}/></div></div><ErrorNote message={failure}/><div className="dialog-actions"><button className="secondary" type="button" onClick={()=>setEdit(null)}>გაუქმება</button><button className="primary" type="submit" disabled={busy||uploading}>{busy?"ინახება…":"შენახვა"}</button></div></fieldset></form>}</DialogContent></Dialog></AdminShell>;
}
