import {ShoppingBag,MapPin,ChefHat,ClipboardList,Store,Package,Settings,Utensils,BarChart3} from "lucide-react";
import {Brand,DemoBanner} from "./brand";
import {type Settings as StoreSettings} from "@/lib/menu";
export function Header({count,onCart}:{count?:number;onCart?:()=>void}){return <><DemoBanner/><header className="site-header"><div className="shell header-inner"><Brand/><nav aria-label="მთავარი ნავიგაცია"><a href="/#menu">მენიუ</a><a href="/orders" className="orders-link"><ClipboardList size={18}/><span>ჩემი შეკვეთები</span></a>{onCart&&<button className="cart-button" onClick={onCart} aria-label={`კალათა — ${count||0} ცალი`}><ShoppingBag size={20}/><span>კალათა</span><b>{count||0}</b></button>}</nav></div></header></>;}
export function Footer({settings}:{settings?:StoreSettings}){return <footer className="shell site-footer"><div><strong>ხინკალიუსი</strong><p><MapPin size={16}/> ბათუმი · გატანა და მიტანა</p></div><div>{settings?.address&&<p>{settings.address}</p>}{settings?.phone&&<a href={`tel:${settings.phone.replace(/[^+\d]/g,"")}`}>{settings.phone}</a>}<p>ფოტოები და ფასები საცდელია.</p></div><a className="staff-link" href="/admin"><ChefHat size={17}/> თანამშრომლის სივრცე</a></footer>;}
const adminLinks=[{href:"/admin",label:"შეკვეთები",icon:ChefHat},{href:"/admin/products",label:"პროდუქტები",icon:Package},{href:"/admin/pos",label:"სწრაფი სალარო",icon:Store},{href:"/admin/statistics",label:"სტატისტიკა",icon:BarChart3},{href:"/admin/settings",label:"პარამეტრები",icon:Settings}];
export function AdminShell({active,children}:{active:string;children:React.ReactNode}){return <><DemoBanner/><header className="admin-header"><div className="shell header-inner"><Brand/><a className="secondary" href="/"><Utensils size={17}/> საიტის ნახვა</a></div></header><div className="admin-nav"><nav className="shell" aria-label="მართვის მენიუ">{adminLinks.map(l=><a key={l.href} href={l.href} aria-current={active===l.href?"page":undefined} className={active===l.href?"active":""}><l.icon size={19}/>{l.label}</a>)}</nav></div><main className="shell admin-main">{children}</main></>;}
export function ErrorNote({message,onRetry}:{message:string;onRetry?:()=>void}){if(!message)return null;return <div role="alert" className="error-box">{message}{onRetry&&<button className="text-button" onClick={onRetry}>ხელახლა ცდა</button>}</div>;}
export function Loading(){return <div className="loading-state" role="status">იტვირთება…</div>;}
