"use client";
import {requestId} from "@/lib/request-id";
import {useI18n} from "./language-provider";
import { useState } from 'react';
import type { Settings, DeliveryZone } from '@/lib/menu';
import { DeliveryMap } from './delivery-map';
export function ZoneSettings({ settings, onChange }: {
    settings: Settings;
    onChange: (zones: DeliveryZone[]) => void;
}) { const { t, locale } = useI18n(); const [selected, setSelected] = useState(settings.zones[0]?.id || ''); const z = settings.zones.find(z => z.id === selected); function edit(update: Partial<DeliveryZone>) { onChange(settings.zones.map(v => v.id === selected ? { ...v, ...update } : v)); } return <section className="settings-card"><h2>{t("მიტანის ზონები")}</h2><p>{t("საწყისი საზღვრები და ტარიფები სატესტოა. მოარგე შენს კურიერს. ზონების გადაკვეთისას სიაში პირველი მოქმედებს.")}</p><div className="zone-tabs">{settings.zones.map(v => <button type="button" key={v.id} className={v.id === selected ? 'primary' : 'secondary'} onClick={() => setSelected(v.id)}>{locale==="en"?v.nameEn:locale==="ru"?v.nameRu:v.name}</button>)}<button type="button" className="secondary" disabled={settings.zones.length >= 20} onClick={() => { const id = requestId(); onChange([...settings.zones, { id, name: "ახალი ზონა", nameEn: 'New zone', nameRu: 'Новая зона', enabled: false, fee: 400, minutes: 20, minimum: 0, polygon: [] }]); setSelected(id); }}>{t("ზონის დამატება")}</button></div>{z && <><div className="form-grid"><label className="field">{t("ზონის სახელი · KA")}<input required maxLength={80} value={z.name} onChange={e => edit({ name: e.target.value })}/></label><label className="field">{t("ზონის სახელი · EN")}<input required maxLength={80} value={z.nameEn} onChange={e => edit({ nameEn: e.target.value })}/></label><label className="field">{t("ზონის სახელი · RU")}<input required maxLength={80} value={z.nameRu} onChange={e => edit({ nameRu: e.target.value })}/></label><label className="field">{t("მიტანის ფასი ₾")}<input type="number" required min="0" max="1000" step="0.01" value={z.fee / 100} onChange={e => edit({ fee: Math.round(Number(e.target.value) * 100) })}/></label><label className="field">{t("გზის დრო, წუთი")}<input type="number" required min="0" max="180" value={z.minutes} onChange={e => edit({ minutes: Number(e.target.value) })}/></label><label className="field">{t("ზონის მინიმალური შეკვეთა ₾")}<input type="number" required min="0" max="1000" step="0.01" value={z.minimum / 100} onChange={e => edit({ minimum: Math.round(Number(e.target.value) * 100) })}/></label></div><label className="check-row"><input type="checkbox" checked={z.enabled} onChange={e => edit({ enabled: e.target.checked })}/>{t("ზონა ჩართულია")}</label><DeliveryMap key={z.id} point={z.polygon.at(-1) ?? null} drawing zones={[z]} onChange={p => { if (z.polygon.length < 50)
    edit({ polygon: [...z.polygon, p] }); }}/><p>{z.polygon.length}{" " + t("/ 50 · კუთხეები") + ""}</p><div className="heading-actions"><button className="secondary" type="button" onClick={() => edit({ polygon: z.polygon.slice(0, -1) })}>{t("ბოლო კუთხის წაშლა")}</button><button className="secondary" type="button" onClick={() => edit({ polygon: [] })}>{t("საზღვრის თავიდან დახაზვა")}</button><button className="secondary" type="button" onClick={() => onChange([z, ...settings.zones.filter(v => v.id !== z.id)])}>{t("პირველ ადგილზე გადატანა")}</button><button className="text-button" type="button" onClick={() => { onChange(settings.zones.filter(v => v.id !== z.id)); setSelected(''); }}>{t("ზონის წაშლა")}</button></div>{z.polygon.length < 3 && <p className="error-box">{t("შენახვამდე მონიშნე მინიმუმ 3 კუთხე ან წაშალე ცარიელი ზონა.")}</p>}</>}</section>; }
