"use client";
import {useMemo} from "react";
import {useI18n} from "@/components/language-provider";
import {localizedProduct,localizedSettings} from "./i18n-core";
import {useCallback,useEffect,useState} from "react";
import {type Product,type Settings} from "./menu";
export async function api<T>(url:string,options?:RequestInit):Promise<T>{let r:Response;try{r=await fetch(url,{...options,cache:"no-store",headers:{...(options?.body&&typeof options.body==="string"?{"Content-Type":"application/json"}:{}),...options?.headers}});}catch(e){if((e as Error).name==="AbortError")throw e;throw new Error("კავშირი ვერ დამყარდა. სცადე ხელახლა.");}let data:unknown;try{data=await r.json();}catch{throw new Error("კავშირი ვერ დამყარდა. სცადე ხელახლა.");}if(!r.ok)throw new Error((data as {error?:string})?.error||"მოქმედება ვერ შესრულდა.");return data as T;}
export function useCatalog(admin=false){const{locale}=useI18n();const[data,setData]=useState<{products:Product[];settings:Settings;workload:{units:number;prepMinutes:number}}|null>(null),[error,setError]=useState("");const load=useCallback(async()=>{try{const next=await api<{products:Product[];settings:Settings;workload:{units:number;prepMinutes:number}}>(admin?"/api/admin/products":"/api/catalog");setData(next);setError("");return next;}catch(e){setError((e as Error).message);return null;}},[admin]);useEffect(()=>{void load();const f=()=>{void load();};window.addEventListener("focus",f);const t=admin?undefined:setInterval(f,30000);return()=>{window.removeEventListener("focus",f);if(t)clearInterval(t);};},[load,admin]);const localized=useMemo(()=>data&&!admin?{...data,products:data.products.map(p=>localizedProduct(p,locale)),settings:localizedSettings(data.settings,locale)}:data,[data,admin,locale]);return{data:localized,error,load};}
export function productPayload(p:Product){const{id,updatedAt,...v}=p;void id;void updatedAt;return{...v,cost:p.cost??0};}
