import messages from './translations.json';
import type {Locale,Product,Settings,OrderItem} from './menu';
export type Translator=(key:string,params?:Record<string,string|number>)=>string;
const dictionary=messages as Record<string,{en:string;ru:string}>;
export function translate(key:string,locale:Locale,params:Record<string,string|number>={}){let value=locale==='ka'?key:dictionary[key]?.[locale]??key;return value.replace(/\{(\w+)\}/g,(match,k)=>String(params[k]??match));}
export function localizedProduct(p:Product,locale:Locale):Product {if(locale==='ka')return p;const custom=p.translations?.[locale];return{...p,name:custom?.name||translate(p.name,locale),description:custom?.description||translate(p.description,locale),ingredients:custom?.ingredients||translate(p.ingredients,locale),allergens:custom?.allergens||translate(p.allergens,locale)};}
export function itemName(p:OrderItem|{name:string;translations?:Product['translations']},locale:Locale){return locale==='ka'?p.name:p.translations?.[locale]?.name||translate(p.name,locale);}
export function localizedSettings(s:Settings,locale:Locale):Settings{if(locale==='ka')return s;const v=s.translations?.[locale];return{...s,address:v?.address||s.address,notice:v?.notice||translate(s.notice,locale),deliveryArea:v?.deliveryArea||translate(s.deliveryArea,locale),zones:s.zones.map(z=>({...z,name:locale==='en'?z.nameEn:z.nameRu}))};}
export function translatedError(message:string,locale:Locale){if(dictionary[message])return translate(message,locale);const patterns:[RegExp,string,string[]][]=[[/^ერთ-ერთი პროდუქტის მინიმუმია (\d+) ცალი\. კალათაში გადაამოწმე\.$/,"ერთ-ერთი პროდუქტის მინიმუმია {quantity} ცალი. კალათაში გადაამოწმე.",["quantity"]],[/^(.+): მინიმუმ (\d+) ცალი\.$/,'{name}: მინიმუმ {quantity} ცალი.',['name','quantity']],[/^მინიმალური შეკვეთა ([\d.]+) ₾\.$/,'მინიმალური შეკვეთა {amount} ₾.',['amount']],[/^ამ ზონის მინიმალური შეკვეთა ([\d.]+) ₾\.$/,'ამ ზონის მინიმალური შეკვეთა {amount} ₾.',['amount']]];for(const [pattern,key,keys] of patterns){const match=message.match(pattern);if(match)return translate(key,locale,Object.fromEntries(keys.map((k,i)=>[k,k==='name'?translate(match[i+1],locale):match[i+1]])));}return message;}
