import {deliveryZone,validPoint} from "./operations";
import { z } from "zod";
import { type Product,type Settings,isOpen } from "./menu";
const point=z.object({lat:z.number().min(-85).max(85),lng:z.number().min(-180).max(180)}).strict();
const productText=z.object({name:z.string().trim().min(2).max(80),description:z.string().trim().max(200),ingredients:z.string().trim().max(500),allergens:z.string().trim().max(250)}).strict();
export const orderInput=z.object({requestKey:z.string().uuid(),point:point.nullable().optional(),name:z.string().trim().max(80),phone:z.string().trim().max(30).transform(v=>v.replace(/[\s()-]/g,"")),address:z.string().trim().max(250),note:z.string().trim().max(500),fulfillment:z.enum(["delivery","pickup"]),source:z.enum(["web","pos"]).default("web"),paymentMethod:z.enum(["cash","terminal"]),expectedTotal:z.number().int().min(0),items:z.array(z.object({id:z.string().min(1).max(180),quantity:z.number().int().min(1).max(200)}).strict()).min(1).max(100)}).strict().superRefine((v,c)=>{
 if(v.source==="web"&&v.name.length<2)c.addIssue({code:"custom",message:"მიუთითე სახელი.",path:["name"]});
 if(v.source==="web"&&!/^\+?[0-9]{8,15}$/.test(v.phone))c.addIssue({code:"custom",message:"მიუთითე სწორი ტელეფონის ნომერი.",path:["phone"]});
 if(v.fulfillment==="delivery"&&v.address.length<5)c.addIssue({code:"custom",message:"მიუთითე სრული მისამართი.",path:["address"]});
 if(v.source==="pos"&&v.fulfillment!=="pickup")c.addIssue({code:"custom",message:"სალაროს შეკვეთა გასატანია.",path:["fulfillment"]});
 if(v.source==="web"&&v.paymentMethod!=="cash")c.addIssue({code:"custom",message:"ონლაინ გადახდა ჯერ არ არის ჩართული.",path:["paymentMethod"]});
 if(new Set(v.items.map(i=>i.id)).size!==v.items.length)c.addIssue({code:"custom",message:"პროდუქტი მეორდება.",path:["items"]});
 if(v.items.reduce((a,b)=>a+b.quantity,0)>500)c.addIssue({code:"custom",message:"მაქსიმუმ 500 ერთეული ერთ შეკვეთაში.",path:["items"]});
});
export function calculateOrder(input:z.infer<typeof orderInput>,products:Product[],settings:Settings){
 if(input.source==="web"&&!isOpen(settings))throw new Error("შეკვეთების მიღება დროებით შეჩერებულია.");
 const items=input.items.map(i=>{const p=products.find(p=>p.id===i.id);if(!p||!p.available)throw new Error("ერთ-ერთი პროდუქტი ამოიწურა. განაახლე კალათა.");if(i.quantity<p.minQuantity)throw new Error(`ერთ-ერთი პროდუქტის მინიმუმია ${p.minQuantity} ცალი. კალათაში გადაამოწმე.`);return{id:p.id,name:p.name,quantity:i.quantity,price:p.price,cost:p.cost??0,category:p.category,translations:p.translations};});
 const subtotal=items.reduce((s,i)=>s+i.quantity*i.price,0);if(input.source==="web"&&subtotal<settings.minimumOrder)throw new Error(`მინიმალური შეკვეთა ${(settings.minimumOrder/100).toFixed(2)} ₾.`);
 const zone=input.fulfillment==="delivery"?deliveryZone(input.point,settings.zones):undefined;if(input.fulfillment==="delivery"&&!zone)throw new Error("მისამართი მიტანის ზონის გარეთაა. აირჩიე გატანა ან გადაამოწმე პინი.");if(zone&&subtotal<zone.minimum)throw new Error(`ამ ზონის მინიმალური შეკვეთა ${(zone.minimum/100).toFixed(2)} ₾.`);const deliveryFee=zone?.fee??0;return{items,subtotal,deliveryFee,total:subtotal+deliveryFee,zone};
}
export const transitions:Record<string,string[]>={received:["cooking","cancelled"],cooking:["ready","cancelled"],ready:["delivering","completed","cancelled"],delivering:["completed","cancelled"],completed:[],cancelled:[]};
export const productInput=z.object({translations:z.object({en:productText,ru:productText}),name:z.string().trim().min(2).max(80),description:z.string().trim().max(200),ingredients:z.string().trim().max(500),allergens:z.string().trim().max(250),category:z.enum(["khinkali","sauce","drink"]),price:z.number().int().min(1).max(1000000),cost:z.number().int().min(0).max(1000000),image:z.string().refine(s=>s==="/khinkali.png"||s===""||/^\/api\/images\/[0-9a-f-]{36}$/.test(s),"ფოტო ატვირთე მოწყობილობიდან."),available:z.boolean(),minQuantity:z.number().int().min(1).max(200)}).strict().superRefine((p,ctx)=>{for(const locale of ["en","ru"] as const)for(const field of ["name","description","ingredients","allergens"] as const)if(p[field]&&!p.translations[locale][field])ctx.addIssue({code:"custom",message:"შენახვამდე შეავსე ინგლისური და რუსული თარგმანები.",path:["translations",locale,field]});});
export const settingsInput=z.object({accepting:z.boolean(),enforceHours:z.boolean(),openTime:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),closeTime:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),prepMinutes:z.number().int().min(5).max(180),deliveryMinutes:z.number().int().min(0).max(180),deliveryFee:z.number().int().min(0).max(100000),minimumOrder:z.number().int().min(0).max(100000),address:z.string().trim().max(250),phone:z.string().trim().max(30),deliveryArea:z.string().trim().max(250),notice:z.string().trim().max(250),translations:z.object({en:z.object({address:z.string().trim().max(250),deliveryArea:z.string().trim().max(250),notice:z.string().trim().max(250)}),ru:z.object({address:z.string().trim().max(250),deliveryArea:z.string().trim().max(250),notice:z.string().trim().max(250)})}).optional(),loadEnabled:z.boolean(),capacity:z.number().int().min(1).max(1000),batchMinutes:z.number().int().min(1).max(180),zones:z.array(z.object({id:z.string().min(1).max(80),name:z.string().trim().min(2).max(80),nameEn:z.string().trim().min(2).max(80),nameRu:z.string().trim().min(2).max(80),enabled:z.boolean(),fee:z.number().int().min(0).max(100000),minutes:z.number().int().min(0).max(180),minimum:z.number().int().min(0).max(100000),polygon:z.array(point).min(3).max(50).refine(points=>Math.abs(points.reduce((a,p,i)=>{const q=points[(i+1)%points.length];return a+p.lng*q.lat-q.lng*p.lat;},0))>0.00000001)}).strict()).max(20).refine(zones=>new Set(zones.map(z=>z.id)).size===zones.length)}).strict();
