import { sqliteTable, text, integer, real, index, uniqueIndex } from "drizzle-orm/sqlite-core";
export const orders=sqliteTable("orders",{
 id:text("id").primaryKey(),ownerId:text("owner_id").notNull(),requestKey:text("request_key").notNull(),requestHash:text("request_hash").notNull(),customerName:text("customer_name").notNull(),phone:text("phone").notNull(),address:text("address").notNull(),note:text("note").notNull(),fulfillment:text("fulfillment").notNull(),itemsJson:text("items_json").notNull(),subtotal:integer("subtotal").notNull(),deliveryFee:integer("delivery_fee").notNull(),total:integer("total").notNull(),status:text("status").notNull().default("received"),paymentStatus:text("payment_status").notNull().default("demo_unpaid"),createdAt:integer("created_at").notNull(),updatedAt:integer("updated_at").notNull(),
 paymentMethod:text("payment_method").notNull().default("demo"),source:text("source").notNull().default("web"),prepMinutes:integer("prep_minutes").notNull().default(25),cashReceived:integer("cash_received"),paymentCollectedAt:integer("payment_collected_at"),deliveryLat:real("delivery_lat"),deliveryLng:real("delivery_lng"),zoneName:text("zone_name").notNull().default(""),zoneNameEn:text("zone_name_en").notNull().default(""),zoneNameRu:text("zone_name_ru").notNull().default(""),travelMinutes:integer("travel_minutes").notNull().default(0),shiftId:text("shift_id"),cashDestination:text("cash_destination").notNull().default("legacy"),
},t=>[uniqueIndex("idx_orders_owner_request").on(t.ownerId,t.requestKey),index("idx_orders_owner_created").on(t.ownerId,t.createdAt),index("idx_orders_owner_collected").on(t.ownerId,t.paymentCollectedAt),index("idx_orders_owner_shift").on(t.ownerId,t.shiftId)]);
export const products=sqliteTable("products",{
 id:text("id").primaryKey(),ownerId:text("owner_id").notNull(),translations:text("translations").notNull().default("{}"),name:text("name").notNull(),description:text("description").notNull(),ingredients:text("ingredients").notNull(),allergens:text("allergens").notNull(),category:text("category").notNull(),price:integer("price").notNull(),cost:integer("cost").notNull(),image:text("image").notNull(),available:integer("available").notNull().default(1),minQuantity:integer("min_quantity").notNull().default(1),updatedAt:integer("updated_at").notNull(),
},t=>[index("idx_products_owner").on(t.ownerId)]);
export const settings=sqliteTable("store_settings",{ownerId:text("owner_id").primaryKey(),value:text("value").notNull(),updatedAt:integer("updated_at").notNull()});

export const expenses=sqliteTable("expenses",{
 id:text("id").primaryKey(),ownerId:text("owner_id").notNull(),requestKey:text("request_key").notNull(),requestHash:text("request_hash").notNull(),amount:integer("amount").notNull(),category:text("category").notNull(),description:text("description").notNull(),paidAt:integer("paid_at").notNull(),createdAt:integer("created_at").notNull(),paymentSource:text("payment_source").notNull(),shiftId:text("shift_id"),voidedAt:integer("voided_at"),voidReason:text("void_reason")
},t=>[uniqueIndex("idx_expense_request").on(t.ownerId,t.requestKey),index("idx_expense_owner_paid").on(t.ownerId,t.paidAt),index("idx_expense_owner_shift").on(t.ownerId,t.shiftId)]);
export const shifts=sqliteTable("cash_shifts",{
 id:text("id").primaryKey(),ownerId:text("owner_id").notNull(),activeOwner:text("active_owner"),requestKey:text("request_key").notNull(),requestHash:text("request_hash").notNull(),openedAt:integer("opened_at").notNull(),closedAt:integer("closed_at"),openingCash:integer("opening_cash").notNull(),expectedCash:integer("expected_cash"),countedCash:integer("counted_cash"),difference:integer("difference"),closeKey:text("close_key"),closeHash:text("close_hash"),note:text("note").notNull().default("")
},t=>[uniqueIndex("idx_shift_active").on(t.activeOwner),uniqueIndex("idx_shift_request").on(t.ownerId,t.requestKey),index("idx_shift_owner_opened").on(t.ownerId,t.openedAt)]);
export const cashMovements=sqliteTable("cash_movements",{
 id:text("id").primaryKey(),ownerId:text("owner_id").notNull(),shiftId:text("shift_id").notNull(),requestKey:text("request_key").notNull(),requestHash:text("request_hash").notNull(),amount:integer("amount").notNull(),kind:text("kind").notNull(),note:text("note").notNull(),createdAt:integer("created_at").notNull()
},t=>[uniqueIndex("idx_cash_move_request").on(t.ownerId,t.requestKey),index("idx_cash_move_shift").on(t.shiftId)]);
