import { sqliteTable, text, integer, index, uniqueIndex } from "drizzle-orm/sqlite-core";
export const orders=sqliteTable("orders",{
 id:text("id").primaryKey(),ownerId:text("owner_id").notNull(),requestKey:text("request_key").notNull(),requestHash:text("request_hash").notNull(),customerName:text("customer_name").notNull(),phone:text("phone").notNull(),address:text("address").notNull(),note:text("note").notNull(),fulfillment:text("fulfillment").notNull(),itemsJson:text("items_json").notNull(),subtotal:integer("subtotal").notNull(),deliveryFee:integer("delivery_fee").notNull(),total:integer("total").notNull(),status:text("status").notNull().default("received"),paymentStatus:text("payment_status").notNull().default("demo_unpaid"),createdAt:integer("created_at").notNull(),updatedAt:integer("updated_at").notNull(),
 paymentMethod:text("payment_method").notNull().default("demo"),source:text("source").notNull().default("web"),prepMinutes:integer("prep_minutes").notNull().default(25),cashReceived:integer("cash_received"),paymentCollectedAt:integer("payment_collected_at"),
},t=>[uniqueIndex("idx_orders_owner_request").on(t.ownerId,t.requestKey),index("idx_orders_owner_created").on(t.ownerId,t.createdAt),index("idx_orders_owner_collected").on(t.ownerId,t.paymentCollectedAt)]);
export const products=sqliteTable("products",{
 id:text("id").primaryKey(),ownerId:text("owner_id").notNull(),name:text("name").notNull(),description:text("description").notNull(),ingredients:text("ingredients").notNull(),allergens:text("allergens").notNull(),category:text("category").notNull(),price:integer("price").notNull(),cost:integer("cost").notNull(),image:text("image").notNull(),available:integer("available").notNull().default(1),minQuantity:integer("min_quantity").notNull().default(1),updatedAt:integer("updated_at").notNull(),
},t=>[index("idx_products_owner").on(t.ownerId)]);
export const settings=sqliteTable("store_settings",{ownerId:text("owner_id").primaryKey(),value:text("value").notNull(),updatedAt:integer("updated_at").notNull()});
