import {z} from 'zod';
import {getDb} from '@/db';
import {currentOwner,apiError,fail,sameOrigin,readBody,payloadHash} from '@/lib/server';
import {SHIFT_SELECT,CLOSE_SHIFT_SQL} from '@/lib/finance';
export const dynamic='force-dynamic';
const key=z.string().uuid(),amount=z.number().int().min(0).max(100000000),note=z.string().trim().max(300);
const schema=z.discriminatedUnion('action',[z.object({action:z.literal('open'),requestKey:key,openingCash:amount,note}).strict(),z.object({action:z.literal('close'),requestKey:key,id:key,countedCash:amount,note}).strict(),z.object({action:z.literal('move'),requestKey:key,id:key,amount:amount.refine(v=>v>0),kind:z.enum(['in','out']),note:note.refine(v=>v.length>=3)}).strict()]);
export async function GET(){const owner=await currentOwner();if(!owner)return fail('შესვლა აუცილებელია.',401);try{const db=getDb(),r=await db.prepare(SHIFT_SELECT+' WHERE owner_id=? ORDER BY opened_at DESC LIMIT 100').bind(owner).all();const active=r.results.find(s=>!s.closed_at);const movements=active?await db.prepare('SELECT * FROM cash_movements WHERE owner_id=? AND shift_id=? ORDER BY created_at DESC').bind(owner,active.id).all():{results:[]};return Response.json({shifts:r.results,movements:movements.results},{headers:{'Cache-Control':'no-store'}});}catch(e){return apiError(e);}}
export async function POST(request:Request){const owner=await currentOwner();if(!owner)return fail('შესვლა აუცილებელია.',401);if(!sameOrigin(request))return fail('მოთხოვნა ვერ დადასტურდა.',403);let b;try{b=schema.parse(await readBody(request));}catch{return fail('შეამოწმე თანხა და ველები.');}try{const db=getDb(),hash=await payloadHash(b),now=Date.now();if(b.action==='open'){const prev=await db.prepare('SELECT * FROM cash_shifts WHERE owner_id=? AND request_key=?').bind(owner,b.requestKey).first();if(prev)return prev.request_hash===hash?Response.json({shift:prev}):fail('ეს მცდელობა უკვე გამოყენებულია. განაახლე ფორმა.',409);await db.prepare('INSERT INTO cash_shifts (id,owner_id,active_owner,request_key,request_hash,opened_at,opening_cash,note) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT DO NOTHING').bind(crypto.randomUUID(),owner,owner,b.requestKey,hash,now,b.openingCash,b.note).run();const row=await db.prepare('SELECT * FROM cash_shifts WHERE owner_id=? AND request_key=?').bind(owner,b.requestKey).first();if(!row)return fail('სალაროს ცვლა უკვე გახსნილია.',409);return row.request_hash===hash?Response.json({shift:row}):fail('ეს მცდელობა უკვე გამოყენებულია. განაახლე ფორმა.',409);}
if(b.action==='close'){const row=await db.prepare('SELECT * FROM cash_shifts WHERE id=? AND owner_id=?').bind(b.id,owner).first();if(!row)return fail('ცვლა ვერ მოიძებნა.',404);if(row.closed_at)return row.close_key===b.requestKey&&row.close_hash===hash?Response.json({shift:row}):fail('ცვლა უკვე დახურულია.',409);const r=await db.prepare(CLOSE_SHIFT_SQL).bind(b.countedCash,b.countedCash,now,b.requestKey,hash,b.note,b.id,owner).run();if(!r.meta.changes){const latest=await db.prepare('SELECT * FROM cash_shifts WHERE id=? AND owner_id=?').bind(b.id,owner).first();if(latest?.close_key!==b.requestKey||latest?.close_hash!==hash)return fail('ცვლა უკვე დახურულია.',409);}return Response.json({ok:true});}
const prev=await db.prepare('SELECT * FROM cash_movements WHERE owner_id=? AND request_key=?').bind(owner,b.requestKey).first();if(prev)return prev.request_hash===hash?Response.json({movement:prev}):fail('ეს მცდელობა უკვე გამოყენებულია. განაახლე ფორმა.',409);await db.prepare('INSERT INTO cash_movements (id,owner_id,shift_id,request_key,request_hash,amount,kind,note,created_at) SELECT ?,?,?,?,?,?,?,?,? WHERE EXISTS(SELECT 1 FROM cash_shifts WHERE id=? AND active_owner=? AND closed_at IS NULL) ON CONFLICT(owner_id,request_key) DO NOTHING').bind(crypto.randomUUID(),owner,b.id,b.requestKey,hash,b.amount,b.kind,b.note,now,b.id,owner).run();const saved=await db.prepare('SELECT * FROM cash_movements WHERE owner_id=? AND request_key=?').bind(owner,b.requestKey).first();if(!saved)return fail('ჯერ გახსენი სალაროს ცვლა.',409);return saved.request_hash===hash?Response.json({movement:saved}):fail('ეს მცდელობა უკვე გამოყენებულია. განაახლე ფორმა.',409);
}catch(e){return apiError(e);}}
